Refactor: Migrate Bootstrap Table to DataGrid Issue #173
mikhael28/paretOS pull request #206
Opened 2022-04-19 01:38 UTC by annovo

Pull-Request for `paretOS`

## Description
- Added `@mui/x-data-grid` package
- Replaced table with DataGrid
- Added StyledDataGrid for custom DataGrid styling

## Relates to
- [Refactor: Migrate one-off Bootstrap Components Table to Material UI](https://github.com/mikhael28/paretOS/issues/173)

## Reviewers
- @mikhael28 
- @jayeclark 

### Notes 
- The selected/hover style is currently aligned with `theme.palette.primary` instead of the original orange styling.
- The rank is displayed for all people instead of "-" for equal ranking. The primary reason for it is confusing results when sorting. Like this: 
<img width="50%" alt="Screen Shot 2022-04-18 at 4 23 53 PM" src="https://user-images.githubusercontent.com/64330181/163902858-67b0be52-7ff7-46b6-b6c9-ac77404c3b4f.png">

### Screenshots / other info

<img width="50%" alt="Screen Shot 2022-04-18 at 6 16 05 PM" src="https://user-images.githubusercontent.com/64330181/163902901-4d852431-20df-4670-8191-2a3c20f9de3b.png">

2022-04-19 15:24 UTC, mikhael28 commented
@annovo thank you for sending this in! You did a great job in recreating the look and feel of the current leaderboard, and did it very quickly.

The thing I am worried about, as the size of the OS (in terms of functionality, and total amount of code) becomes bigger, is performance and bundle size. The one nice thing about the `react-bootstrap` table, is that it is only 15kb
<img width="439" alt="Screen Shot 2022-04-19 at 8 14 26 AM" src="https://user-images.githubusercontent.com/15205259/164037065-331062a4-27f3-4d49-a58f-6e73d3665b00.png">

However, looking at my favorite site bundlephobia, I can see that the `mui/x-data-grid` community edition is coming in at 450kb, 120kb gzipped. So, it's a 10x increase in size for maybe 1.5x improvement in functionality.
<img width="1507" alt="Screen Shot 2022-04-19 at 8 12 52 AM" src="https://user-images.githubusercontent.com/15205259/164037384-8aefe255-eafc-4ef3-90ec-3d0672f5277d.png">

For context, the 'main' application bundle that is required for download before true functionality can be activated is 442kb.
<img width="402" alt="Screen Shot 2022-04-19 at 8 20 32 AM" src="https://user-images.githubusercontent.com/15205259/164038409-247bdf8c-56a3-4a12-8946-9aaaaaab2613.png">
 Here is the screenshot of the JavaScript bundles (we are using bundle splitting/lazy loading to dynamically download them at run-time, to reduce the initial bundle size, so that the download length is less and our time to paint is faster! More details on web vitals: https://web.dev/vitals/

Before we can agree to move forward with this package, I would like you to look at a few things.

1. Can you run `yarn build` and upload a screenshot of the impact on the bundle size, compared to the one I posted above. You can also use lazy loading/bundle splitting on the Leaderboard component to try and decrease the impact, refer to `Routes.js` to see how this is done.
2. Can you research what other react table components are out there? Especially, are there any that are razor focused on performance and bundle size? This is a good article to start with: https://blog.logrocket.com/the-top-react-table-libraries-to-use-in-2021/#:~:text=React%20Table%20is%20a%20lightweight,14kb)%2C%20composable%20and%20extensible.
3. Based on your research, can you present the three best candidates for us?

Again, thank you for doing the initial work here - the mui/x-data-grid professional package certainly looks compelling - in their demo on the website, it easily renders 3 million cells - crazy! I think for us, that might be a little overkill :)

I took some time to write this comment out, I hope it will be a helpful experience to learn to focus on bundle size and performance!

2022-04-19 15:24 UTC, mikhael28 requested changes

2022-04-19 15:24 UTC, mikhael28 commented on package.json
> +    "@mui/x-data-grid": "^5.9.0",
Refer to my comment in the PR!

2022-04-19 15:25 UTC, mikhael28 commented
You can run also run `yarn run analyze`, if you installed `source-map-explorer`, to create a visual matrix of the bundle size as well!

2022-04-19 17:02 UTC, jayeclark commented
This one is on me, for suggesting using DataGrid without thinking to look at the size of the bundle. (I was thinking ahead to a time when we'll need to display hundreds or thousands of accounts compared to how the component is currently used.)

The basic Table component probably does what's needed right now perfectly fine and is only slightly larger than bootstrap. 
<img width="484" alt="Screen Shot 2022-04-19 at 12 50 09 PM" src="https://user-images.githubusercontent.com/84106309/164056856-12a57048-f523-4a26-90c8-186a810b1ce3.png">

2022-04-19 21:00 UTC, mikhael28 commented
The basic Table component would work great for right now! @annovo does that sound good?

2022-04-19 21:11 UTC, annovo commented
I used lazy loading of Board component and here what I got
<img width="40%" alt="Screen Shot 2022-04-19 at 1 27 47 PM" src="https://user-images.githubusercontent.com/64330181/164091099-8a0cc165-5cda-4f2b-8fd1-d7d0872275e4.png">

Surely the third bundle size is due to DataGrid component
<img width="50%" alt="Screen Shot 2022-04-19 at 1 32 58 PM" src="https://user-images.githubusercontent.com/64330181/164091156-7fc17f40-77bc-4a33-a740-da3924bdec0c.png">

I agree that the Table MUI component should be fine.

For example, react-table (55k/15.4k) provides a lot of hooks and definitely can be useful in some cases. However, with the existing functionality this much is unnecessary. Also, it is possible to write custom hooks from the existing sort/filter functions for the table. 
react-virtulized(118k)/react-window(24k) can be used in the future for large data. Here the [example]( https://codesandbox.io/s/je8fbn?file=/demo.tsx) of using it with MUI.

2022-04-19 21:26 UTC, annovo commented
> The basic Table component would work great for right now! @annovo does that sound good?

whoops, sorry, haven't noticed. Yes, I can do the basic Table. Should I make a new PR?

2022-04-19 21:31 UTC, jayeclark commented
@annovo I think it would be fine to just push a new commit to this branch (or even force-push a new one rewriting the last two.) I don't know how you feel about your merged-vs-closed-PR ratio, but personally I like to keep mine high. 😄 And this wasn't an error on your part, it was an oversight on mine!

2022-04-20 17:41 UTC, mikhael28 commented
@annovo thank you for posting the bundle size on the x-data-grid - yes, let's go ahead and integrate the basic Table component from MUI. Let's keep it on this PR :) just make a few new commits and push up the changes!

2022-04-21 16:44 UTC, annovo commented
New table looks pretty much the same
<img width="50%" alt="Screen Shot 2022-04-21 at 9 43 04 AM" src="https://user-images.githubusercontent.com/64330181/164510011-bf400037-6891-4ae0-9994-37e411a1e64b.png">

2022-04-22 17:30 UTC, mikhael28 approved these changes
Great work! The Leaderboard looks great, we are one step closer to ridding ourselves of the accursed `react-bootstrap`!

2022-04-22 17:30 UTC, merged