Update quotes
mikhael28/paretOS pull request #239
Opened 2022-05-08 10:18 UTC by Ngoakor12

Pull-Request for `paretOS`

## Description
- Refactored structure of quotes to easely incorporate mutiple quotes from the same author therefore reducing duplication.
- Added getRandomQuote function in same directory to work with the new quotes structure.
- Added 5 new quotes.

## Reviewers
- @mikhael28

2022-05-11 16:11 UTC, jayeclark requested changes
Great PR, thank you so much for the contribution! The new flow of getting and using quotes is much cleaner.

I had only one very minor change request, related to yarn.lock.

2022-05-11 16:11 UTC, jayeclark commented on src/libs/quotes.ts
> +
This structure (random author and then random author's quote) is great - a contributor who's a big fan of a particular author can add in a bunch of quotes for them, but it won't cause the unintended side where 90% of the quotes that are served up are from that author. :)

2022-05-11 16:38 UTC, Ngoakor12 commented on yarn.lock
> +"@types/minimist@^1.2.0":
Thanks for having a look, appreciate the feedback. I'll merge in new changes now now.

2022-05-13 13:43 UTC, merged

2022-05-14 17:31 UTC, mikhael28 commented
Thank you @Ngoakor12 !

2022-05-14 17:31 UTC, mikhael28 commented
And you of course @jayeclark for reviewing :D