♻️ refactor(SuggestionModal): convert class based component to hooks
mikhael28/paretOS pull request #73
Opened 2021-09-03 10:57 UTC by akashshyamdev

PR for issue #65

2021-09-03 15:51 UTC, mikhael28 commented
@akashshyamdev currently get download speeds of 12kb/sec, and I haven't yet pulled down your repository. I would take hours to download the code and node_modules, so I will be reviewing later in the day. It's likely night time where you are anyway - will have an update on your two PR's soon! The one thing I would add, is that regarding the Prettier linting - I don't have any Prettier config, I literally just use the standard options on the base extension. Please run the linter on this file and recommit, if you haven't already - if you look at the diff for that commit, the spacing seems off (though that MIGHT be unrelated to the linter).

2021-09-04 00:37 UTC, mikhael28 commented
Upon opening the Suggestion modal, things are immediately broken. And looking at the code, you need to make the same updates to the state handleChange function - as in the other PR you sent in. It almost seems like you didn't truly test the code, before sending the pull-request :) Please make sure to always run the code and test it before submitting it for PR. You should never, ever send broken code in a PR.
<img width="839" alt="Screen Shot 2021-09-03 at 5 36 05 PM" src="https://user-images.githubusercontent.com/15205259/132076634-5e3dc716-5a9a-472b-9805-0599b5f7923e.png">

2021-09-04 04:39 UTC, akashshyamdev commented
@mikhael28in which routes are these files displayed i.e. how do I get to this page?

2021-09-04 05:51 UTC, mikhael28 commented
@akashshyamdev The easiest way to find out where these files are displayed is to figure out where it's being mounted in the JSX code. You can use 'Command+Shift+F' and search for SuggestionModal to see in what file is that React component being mounted. Then, you can check the `Routes.js` to see what route that particular component is assigned to. Sometimes, you have to do a little bit of digging in the repository. For the sake of your learning, I'm not giving you the answer directly - I'm trying to teach you how to find it for yourself :D

As a friendly piece of open-source advice, ask this question before you send in a pull-request :) if you cannot confirm that you have working code, wait to send a pull-request. I appreciate the desire to contribute code, and you have been doing a really great job being productive the last couple of days.

2021-09-04 07:45 UTC, akashshyamdev commented on src/context/SuggestionModal.js
>  import DialogContent from "@material-ui/core/DialogContent";
Test

2021-09-04 10:25 UTC, akashshyamdev commented
Sorry about the bugs, I have fixed that now. Also, I've fixed up the UI. Thanks for the advice mate 👍

2021-09-04 16:15 UTC, mikhael28 requested changes
Great work - I'm now request a few UI changes, functionality things are good!

2021-09-04 16:15 UTC, mikhael28 commented on src/context/SuggestionModal.js
> +				<DialogContentText style={{ fontSize: "24px" }}>
Can you make this font smaller, perhaps 18px?

2021-09-04 16:15 UTC, mikhael28 commented on src/context/SuggestionModal.js
> +					<ControlLabel style={{ fontSize: "16px" }}>Description</ControlLabel>
Make this 14px please

2021-09-04 16:15 UTC, mikhael28 commented on src/context/SuggestionModal.js
> +				<h1>Suggestion for {schema}</h1>
Can you add in the string formatting that you mentioned here? https://github.com/mikhael28/paretOS/issues/65
To make it capitalized, etc?

2021-09-05 05:08 UTC, akashshyamdev commented
Ok @mikhael28, I've completed the changes :)

2021-09-05 17:39 UTC, mikhael28 commented
Great work, thank you for working through all the changes and reviews! Merging in :D

2021-09-05 17:39 UTC, merged